// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKMnXZ0d5GciIruQeaRPYPPXtkfErDpI',
    appId: '1:492187444908:android:735aba992d771e75b06109',
    messagingSenderId: '492187444908',
    projectId: 'flutter-havea-chat',
    storageBucket: 'flutter-havea-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCblt_97qQPRF0UW2fKDOGh7uMBnY2vTsk',
    appId: '1:492187444908:ios:af7288cb2d70ed8bb06109',
    messagingSenderId: '492187444908',
    projectId: 'flutter-havea-chat',
    storageBucket: 'flutter-havea-chat.firebasestorage.app',
    iosBundleId: 'com.example.haveachat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFNwVg5bz09KjlcgRTk3a1FhSuT09G2gw',
    appId: '1:492187444908:web:b7c5148fbc22de93b06109',
    messagingSenderId: '492187444908',
    projectId: 'flutter-havea-chat',
    authDomain: 'flutter-havea-chat.firebaseapp.com',
    storageBucket: 'flutter-havea-chat.firebasestorage.app',
  );

}